(function($){$.fn.powerkitLightbox=function(options){var settings=$.extend({gallery:false,},options);var objSelector=this;var imageSelector=null;var containerSelector=null;$(objSelector).each(function(){if($(this).is('img')){imageSelector=this;}else{imageSelector=$(this).find('img');}
$(imageSelector).each(function(){var container=$(this).parent();if(!$(container).is('a')){return;}
var imagehref=$(container).attr('href');if(!imagehref.match(/\.(gif|jpeg|jpg|png)/)){return;}
if(!($(container).closest('figure').length)){$(container).wrap('<figure class="pk-lightbox-container"></figure>');}
if(!$(container).closest('figure').hasClass('pk-lightbox-container')){$(container).closest('figure').addClass('pk-lightbox-container');}
var imgClasses=['alignnone','aligncenter','alignleft','alignright'];imgClasses.forEach(function(el){if($(container).find('img').hasClass(el)){$(container).find('img').removeClass(el);$(container).find('img').closest('figure').addClass(el);var imgWidth=$(container).find('img').attr('width');if(parseInt(imgWidth)!=='NaN'){$(container).find('img').closest('figure').width(imgWidth);}}});container=$(container).parent();$('> a',container).not('.pk-pin-it').addClass('pk-image-popup');if(powerkit_lightbox_localize.zoom_icon){$('> a',container).not('.pk-pin-it').addClass('pk-zoom-icon-popup');}
if($(objSelector).is('img')){containerSelector=container;}});if(!$(objSelector).is('img')){containerSelector=this;}
$(containerSelector).magnificPopup({delegate:'.pk-image-popup',type:'image',tClose:powerkit_lightbox_localize.text_close+'(Esc)',tLoading:powerkit_lightbox_localize.text_loading,gallery:{enabled:settings.gallery,tPrev:powerkit_lightbox_localize.text_previous,tNext:powerkit_lightbox_localize.text_next,tCounter:'<span class="mfp-counter">%curr% '+powerkit_lightbox_localize.text_counter+' %total%</span>'},image:{titleSrc:function(item){return item.el.closest('figure').find('.wp-caption-text').text();}},});});};function initPowerkitLightbox(){var excludeSelectors=powerkit_lightbox_localize.exclude_selectors;var imageSelectors=powerkit_lightbox_localize.single_image_selectors;var gallerySelectors=powerkit_lightbox_localize.gallery_selectors
var filterSelectors=null;var filterPowerkitLightbox=function(){if(filterSelectors){if($(this).closest(filterSelectors).length>0){return false;}}
return true;}
$(imageSelectors).imagesLoaded(function(){var exSplit=excludeSelectors.split(',');var glSplit=gallerySelectors.split(',');filterSelectors=exSplit.concat(glSplit).filter(function(value){return!!value;}).filter(function(value){return!this[value]&&(this[value]=true);},Object.create(null)).join(',');$(imageSelectors).filter(filterPowerkitLightbox).powerkitLightbox();});$(gallerySelectors).imagesLoaded(function(){filterSelectors=excludeSelectors;$(gallerySelectors).filter(filterPowerkitLightbox).powerkitLightbox({gallery:true});});}
$(document).ready(function(){initPowerkitLightbox();$(document.body).on('post-load image-load',function(){initPowerkitLightbox();});});})(jQuery);