(function($){"use strict";function throttle(func,ms){var isThrottled=false,savedArgs,savedThis;function wrapper(){if(isThrottled){savedArgs=arguments;savedThis=this;return;}
func.apply(this,arguments);isThrottled=true;setTimeout(function(){isThrottled=false;if(savedArgs){wrapper.apply(savedThis,savedArgs);savedArgs=savedThis=null;}},ms);}
return wrapper;}
$.fn.isInViewport=function(){var elementTop=$(this).offset().top;var elementBottom=elementTop+$(this).outerHeight();var viewportTop=$(window).scrollTop();var viewportBottom=viewportTop+$(window).height();return elementBottom>viewportTop&&elementTop<viewportBottom;};$(document).ready(function(){objectFitImages();});$('.cs-post-carousel-items').imagesLoaded(function(instance){var rtl=$('body').hasClass('rtl')?true:false;$(instance.elements).each(function(index,el){$(el).flickity({cellAlign:rtl?'right':'left',wrapAround:true,contain:true,autoPlay:false,adaptiveHeight:false,prevNextButtons:false,pageDots:true,rightToLeft:rtl,on:{ready:function(){$(el).addClass('is-animate');}}});var container=$(el).parents('.cs-post-carousel');$(container).find('.carousel-previous').on('click',function(event){event.preventDefault();var type=rtl?'next':'previous';$(el).flickity(type,true);});$(container).find('.carousel-next').on('click',function(event){event.preventDefault();var type=rtl?'previous':'next';$(el).flickity(type,true);});});});$('.pk-widget-posts-template-carousel > ul').imagesLoaded(function(instance){var rtl=$('body').hasClass('rtl')?true:false;$(instance.elements).each(function(index,el){$(el).flickity({wrapAround:true,adaptiveHeight:true,prevNextButtons:false,pageDots:true,rightToLeft:rtl,on:{ready:function(){$(el).addClass('is-animate');}}});});});$('.footer-instagram-modern .pk-alt-instagram-items').imagesLoaded(function(instance){var requestId;var rtl=$('body').hasClass('rtl')?true:false;$(instance.elements).each(function(index,el){const mainTicker=new Flickity(el,{freeScroll:'stepwise'===csco_config.instagram_animation?false:true,percentPosition:'stepwise'===csco_config.instagram_animation?false:true,autoPlay:false,pauseAutoPlayOnHover:false,accessibility:true,resize:true,wrapAround:true,prevNextButtons:false,pageDots:false,setGallerySize:true,rightToLeft:rtl,on:{ready:function(){$(el).addClass('is-animate');}}});mainTicker.initAnimation=false;mainTicker.x=0;function flickity_play(){if('continuous'===csco_config.instagram_animation){mainTicker.x=mainTicker.x-0.75;mainTicker.settle(mainTicker.x);requestId=window.requestAnimationFrame(flickity_play);}else{mainTicker.playPlayer();}}
function flickity_pause(){if('continuous'===csco_config.instagram_animation){if(requestId){window.cancelAnimationFrame(requestId);requestId=undefined;}}else{mainTicker.stopPlayer();}}
function flickity_init(){var isInView=$(el).isInViewport();if(isInView){if(!mainTicker.initAnimation){flickity_play();mainTicker.initAnimation=true;}}else{flickity_pause();mainTicker.initAnimation=false;}}
$(window).on('load scroll resize scrollstop',function(){flickity_init();});$(document).ready(function(){flickity_init();});$(el).find('.pk-alt-instagram-link img').on('mouseenter focusin',e=>{flickity_pause();});$(el).find('.pk-alt-instagram-link img').on('mouseleave',e=>{flickity_play();});});});$(document).on('click','.post-comments-show button',function(e){$(this).parent().siblings('.post-comments').show();$(this).parent().remove();});(function(){var ticking=false;var update=function(){$('.content-area .site-main').each(function(){var content=$(this).find('.entry-content');var sidebar=$(this).find('.post-sidebar-inner');var offsetTop=20;var offsetBottom=-20;var elements=[];elements.push('> .alignfull');elements.push('> .alignwide');var layouts=$(content).find(elements.join(','));if(0===sidebar.length){return;}
if(0===layouts.length){return;}
var disabled=false;var sidebarTop=$(sidebar).offset().top;var sidebarHeight=$(sidebar).outerHeight(true);for(let i=0;i<$(layouts).length;++i){if('none'===$(layouts[i]).css('transform')){continue;}
let layoutTop=$(layouts[i]).offset().top;let layoutHeight=$(layouts[i]).outerHeight(true);let pointTop=layoutTop-offsetTop;let pointBottom=layoutTop+layoutHeight+offsetBottom;if(sidebarTop+sidebarHeight>=pointTop&&sidebarTop<=pointBottom){disabled=true;}}
if(disabled){$(sidebar).css('opacity','0');}else{$(sidebar).css('opacity','1');}});$('.content-area .site-main').each(function(){var content=$(this).find('.entry-content');var pagination=$(this).find('.post-prev-next-along article');var offsetTop=-20;var offsetBottom=-150;var elements=[];elements.push('> .alignfull');var layouts=$(content).find(elements.join(','));if(0===pagination.length){return;}
if(0===layouts.length){return;}
var disabled=false;var paginationTop=$(pagination).offset().top;var paginationHeight=$(pagination).outerHeight(true);for(let i=0;i<$(layouts).length;++i){if('none'===$(layouts[i]).css('transform')){continue;}
let layoutTop=$(layouts[i]).offset().top;let layoutHeight=$(layouts[i]).outerHeight(true);let pointTop=layoutTop-offsetTop;let pointBottom=layoutTop+layoutHeight+offsetBottom;if(paginationTop+paginationHeight>=pointTop&&paginationTop<=pointBottom){disabled=true;}}
if(disabled){$(pagination).parent().css('opacity','0');$(pagination).parent().css('visibility','hidden');}else{$(pagination).parent().css('opacity','1');$(pagination).parent().css('visibility','visible');}});ticking=false;};var requestTick=function(){if(!ticking){window.requestAnimationFrame(update);ticking=true;}};var onProcess=function(){requestTick();};$(window).on('scroll',onProcess);$(window).on('resize',onProcess);$(window).on('image-load',onProcess);$(window).on('post-load',onProcess);})();if(typeof csco_ajax_pagination!=='undefined'){$('.post-archive').append('<div class="ajax-navigation"><button class="load-more">'+csco_ajax_pagination.translation.load_more+'</button></div>');var query_data=$.parseJSON(csco_ajax_pagination.query_data),infinite=$.parseJSON(query_data.infinite_load),button=$('.ajax-navigation .load-more'),page=2,loading=false,scrollHandling={allow:infinite,reallow:function(){scrollHandling.allow=true;},delay:400};}
function csco_ajax_get_posts(){loading=true;button.addClass('loading');var data={action:'csco_ajax_load_more',page:page,posts_per_page:csco_ajax_pagination.posts_per_page,query_data:csco_ajax_pagination.query_data,_ajax_nonce:csco_ajax_pagination.nonce,};var csco_pagination_url;if('ajax_restapi'===csco_ajax_pagination.type){csco_pagination_url=csco_ajax_pagination.rest_url;}else{csco_pagination_url=csco_ajax_pagination.url;}
$.post(csco_pagination_url,data,function(res){if(res.success){var data=$(res.data.content);if(data.length){var cscoAppendEnd=function(){$(document.body).trigger('post-load');if($('#fb-root').length){FB.XFBML.parse();}
button.removeClass('loading').blur();page=page+1;loading=false;};if($('.post-archive .archive-wrap').hasClass('archive-type-mixed')){for(var key in data){if(key%1!==0){continue;}
var last_section=$('.archive-wrap .archive-main').last();var last_posts=$(last_section).find('article').length;var last_class=$(last_section).attr('class');var new_section=false;var point_end=4;if($('.site-content').hasClass('sidebar-disabled')){point_end=6;}
if($(last_section).hasClass('archive-full')){new_section='archive-grid';}
if($(last_section).hasClass('archive-grid')&&last_posts===point_end){new_section='archive-full';}
if(new_section){$('<div></div>').appendTo('.archive-wrap').addClass(last_class).removeClass('archive-full archive-grid').addClass(new_section);}
$('.archive-wrap .archive-main').last().append(data[key]);}
cscoAppendEnd();}else{if($('.post-archive .archive-main').hasClass('archive-masonry')){data.imagesLoaded(function(){$('.post-archive .archive-main').colcade('append',data);cscoAppendEnd();});}else{$('.post-archive .archive-main').append(data);cscoAppendEnd();}}}
if(res.data.posts_end||!data.length){$('.ajax-navigation').remove();}}else{}}).fail(function(xhr,textStatus,e){});}
if(typeof csco_ajax_pagination!=='undefined'){$(window).scroll(function(){if(button.length&&!loading&&scrollHandling.allow){scrollHandling.allow=false;setTimeout(scrollHandling.reallow,scrollHandling.delay);var offset=$(button).offset().top-$(window).scrollTop();if(4000>offset){csco_ajax_get_posts();}}});$('body').on('click','.load-more',function(){if(!loading){csco_ajax_get_posts();}});}
if(typeof csco_ajax_nextpost!=='undefined'){var objNextparent=$('.site-primary > .site-content'),objNextsect='.cs-nextpost-section',objNextpost=null,currentNTitle=document.title,currentNLink=window.location.href,loadingNextpost=false,scrollNextpost={allow:true,reallow:function(){scrollNextpost.allow=true;},delay:400};if(csco_ajax_nextpost.next_post){$(objNextparent).after('<div class="cs-nextpost-inner"></div>');objNextpost=$('.cs-nextpost-inner');}}
function csco_ajax_get_nextpost(){loadingNextpost=true;var data={action:'csco_ajax_load_nextpost',not_in:csco_ajax_nextpost.not_in,current_user:csco_ajax_nextpost.current_user,nonce:csco_ajax_nextpost.nonce,next_post:csco_ajax_nextpost.next_post,};var csco_ajax_nextpost_url;if('ajax_restapi'===csco_ajax_nextpost.type){csco_ajax_nextpost_url=csco_ajax_nextpost.rest_url;}else{csco_ajax_nextpost_url=csco_ajax_nextpost.url;}
$.post(csco_ajax_nextpost_url,data,function(res){csco_ajax_nextpost.next_post=false;if(res.success){var data=$(res.data.content);if(data.length){loadingNextpost=false;csco_ajax_nextpost.not_in=res.data.not_in;csco_ajax_nextpost.next_post=res.data.next_post;$(objNextpost).siblings('.cs-nextpost-loading').remove();$(objNextpost).append(data);if($('#fb-root').length){FB.XFBML.parse();}
$(document.body).trigger('post-load');}}else{}}).fail(function(xhr,textStatus,e){});}
if(typeof csco_ajax_nextpost!=='undefined'){$(window).scroll(function(){var scrollTop=$(window).scrollTop();if(csco_ajax_nextpost.next_post){if(objNextpost.length&&!loadingNextpost&&scrollNextpost.allow){scrollNextpost.allow=false;setTimeout(scrollNextpost.reallow,scrollNextpost.delay);let offset=objNextpost.offset().top+objNextpost.innerHeight()-scrollTop;if(4000>offset){$(objNextpost).after('<div class="cs-nextpost-loading"></div>');csco_ajax_get_nextpost();}}}
let objFirst=$(objNextsect).first();if(objFirst.length){let firstTop=$(objFirst).offset().top;if(scrollTop<firstTop&&window.location.href!==currentNLink){document.title=currentNTitle;window.history.pushState(null,currentNTitle,currentNLink);}}
$(objNextsect).each(function(index,elem){let elemTop=$(elem).offset().top;let elemHeight=$(elem).innerHeight();if(scrollTop>elemTop&&scrollTop<elemTop+elemHeight){if(window.location.href!==$(elem).data('url')){document.title=$(elem).data('title');window.history.pushState(null,$(elem).data('title'),$(elem).data('url'));if(typeof gtag==='function'&&typeof window.gaData==='object'){var trackingId=Object.keys(window.gaData)[0];if(trackingId){gtag('config',trackingId,{'page_title':$(elem).data('title'),'page_location':$(elem).data('url')});gtag('event','page_view',{'send_to':trackingId});}}}}});});}
function initMasonrySidebar(){var masonrySidebar=$('.sidebar-area'),masonrySidebarOptions={columns:'.sidebar',items:'.widget'};$(masonrySidebar).imagesLoaded(function(){$(masonrySidebar).colcade(masonrySidebarOptions);});}
$(document).ready(function(){initMasonrySidebar();});function initMasonry(){var masonryArchive=$('.archive-masonry'),masonryArchiveOptions={columns:'.archive-col',items:'article'};$(masonryArchive).imagesLoaded(function(){$(masonryArchive).colcade(masonryArchiveOptions);});}
$(document).ready(function(){initMasonry();});function cscoLoadMenuPosts(menuItem){var dataCat=menuItem.children('a').data('cat'),dataType=menuItem.children('a').data('type'),dataNumberposts=menuItem.children('a').data('numberposts'),menuContainer,postsContainer;if(menuItem.hasClass('cs-mega-menu-has-category')){menuContainer=menuItem;postsContainer=menuContainer.find('.cs-mm-posts');}else{menuContainer=menuItem.closest('.sub-menu');postsContainer=menuContainer.find('.cs-mm-posts[data-cat="'+dataCat+'"]');}
menuContainer.find('.menu-item, .cs-mm-posts').removeClass('active-item');menuItem.addClass('active-item');if(postsContainer){postsContainer.addClass('active-item');}
if(menuItem.hasClass('cs-mm-loading')||menuItem.hasClass('cs-mm-loaded')){return false;}
if(!dataCat||typeof dataCat==='undefined'){return false;}
if(!postsContainer||typeof postsContainer==='undefined'){return false;}
var data={'cat':dataCat,'type':dataType,'per_page':dataNumberposts};$.ajax({url:csco_mega_menu.rest_url,type:'GET',data:data,global:false,async:true,beforeSend:function(){menuItem.addClass('cs-mm-loading');postsContainer.addClass('cs-mm-loading');},success:function(res){if(res.status&&'success'===res.status){menuItem.addClass('cs-mm-loaded');postsContainer.addClass('cs-mm-loaded');if(res.content&&res.content.length){$(res.content).imagesLoaded(function(){postsContainer.html(res.content);});}}},complete:function(){menuItem.removeClass('cs-mm-loading');postsContainer.removeClass('cs-mm-loading');}});}
function cscoGetFirstTab(container){var firstTab=false;container.find('.cs-mega-menu-child').each(function(index,el){if($(el).hasClass('menu-item-object-category')){firstTab=$(el);return false;}
if($(el).hasClass('menu-item-object-post_tag')){firstTab=$(el);return false;}});return firstTab;}
$(document).ready(function(){$('.navbar-nav .menu-item.cs-mega-menu-has-category, .navbar-nav .menu-item.cs-mega-menu-child').on('hover',function(){cscoLoadMenuPosts($(this));});$('.navbar-nav .menu-item.cs-mega-menu-has-categories').on('hover',function(){var tab=cscoGetFirstTab($(this));if(tab){cscoLoadMenuPosts(tab);}});});$(document,'.navbar-nav').ready(function(){var tab=false;$('.navbar-nav .menu-item.cs-mega-menu-has-categories').each(function(index,el){tab=cscoGetFirstTab($(this));if(tab){cscoLoadMenuPosts(tab);}});$('.navbar-nav .menu-item.cs-mega-menu-has-category').each(function(index,el){cscoLoadMenuPosts($(this));});});$.fn.responsiveNav=function(){this.removeClass('menu-item-expanded');if(this.prev().hasClass('submenu-visible')){this.prev().removeClass('submenu-visible').slideUp(350);this.parent().removeClass('menu-item-expanded');}else{this.parent().parent().find('.menu-item .sub-menu').removeClass('submenu-visible').slideUp(350);this.parent().parent().find('.menu-item-expanded').removeClass('menu-item-expanded');this.prev().toggleClass('submenu-visible').hide().slideToggle(350);this.parent().toggleClass('menu-item-expanded');}};$(document).ready(function(e){$('.widget_nav_menu .menu-item-has-children').each(function(e){$(this).append('<span></span>');$('> span',this).on('click',function(e){e.preventDefault();$(this).responsiveNav();});if('#'===$('> a',this).attr('href')){$('> a',this).on('click',function(e){e.preventDefault();$(this).next().next().responsiveNav();});}});});var cscoNavigation={};(function(){var $this;cscoNavigation={sScrollAllow:false,sInFirst:true,sInterval:0,sPrevious:0,sDirection:0,loadStickyOffset:0,loadAdminBar:false,Sticky:$('body').hasClass('navbar-sticky-enabled'),StickyUp:$('body').hasClass('navbar-smart-enabled'),StickyNav:$('.site-header .navbar-primary'),StickyHeader:$('.site-header'),StickyOffsetType:'auto',StickyOffset:0,StickyOffsetFull:0,init:function(e){$this=cscoNavigation;$this.events(e);},events:function(e){document.addEventListener('DOMContentLoaded',function(e){$this.stickyInit(e);$this.smartLevels(e);$this.adaptTablet(e);});window.addEventListener('resize',function(e){$this.stickyInit(e);$this.smartLevels(e);$this.adaptTablet(e);});window.addEventListener('scroll',function(e){window.requestAnimationFrame($this.stickyScroll);});$(document).on('animate-search',function(e){$this.animateSearch(e);});$(document).on('animate-search-start',function(e){$this.animateSearchStart(e);});$(document).on('animate-search-done',function(e){$this.animateSearchDone(e);});},stickyInit:function(e){if(!$this.Sticky){return;}
$this.sScrollAllow=false;if($this.StickyOffsetType!=='size'){var calcbar=0;var wpadminbar=0;if($('#wpadminbar').length>0){calcbar=$('#wpadminbar').outerHeight();wpadminbar=calcbar;if('resize'!==e.type){$this.loadAdminBar=wpadminbar;}
if('absolute'===$('#wpadminbar').css('position')){wpadminbar=0;if('resize'!==e.type){$this.loadAdminBar=0;}}}
$this.StickyOffsetFull=$this.StickyHeader.outerHeight();var elOffset=$this.StickyNav.not('.sticky-nav').offset();if(elOffset&&!$this.StickyNav.hasClass('.sticky-nav')){$this.StickyOffset=elOffset.top;$this.loadStickyOffset=elOffset.top;}else{$this.StickyOffset=$this.loadStickyOffset;}
if(32===$this.loadAdminBar){if(46===calcbar){$this.StickyOffset=$this.StickyOffset-wpadminbar+14;}else{$this.StickyOffset=$this.StickyOffset-wpadminbar;}}else if(46===$this.loadAdminBar||0===$this.loadAdminBar){if(32===calcbar){$this.StickyOffset=$this.StickyOffset-wpadminbar-14;}else{$this.StickyOffset=$this.StickyOffset-wpadminbar;}}}
var navHeight=$this.StickyNav.outerHeight();$this.StickyHeader.data('min-height',$this.StickyOffsetFull-navHeight);if('resize'!==e.type){$this.StickyNav.after('<div class="navbar-dummy"></div>');$this.StickyHeader.find('.navbar-dummy').height(navHeight);if($this.StickyUp){$this.StickyHeader.addClass('sticky-type-slide');}}
$this.sScrollAllow=true;},stickyScroll:function(e){if(!$this.sScrollAllow){return;}
var scrollCurrent=$(window).scrollTop();if($this.StickyUp){if(scrollCurrent>$this.StickyOffsetFull){$this.StickyNav.addClass('sticky-nav');}
if(scrollCurrent<=$this.StickyOffset){$this.StickyNav.removeClass('sticky-nav');}
if(scrollCurrent>$this.sPrevious){$this.sInterval=0;$this.sDirection='down';$this.StickyNav.addClass('sticky-down').removeClass('sticky-up');}else{$this.sInterval+=$this.sPrevious-scrollCurrent;$this.sDirection='up';$this.StickyNav.addClass('sticky-up').removeClass('sticky-down');}
if($this.sInterval>150&&'up'===$this.sDirection){$this.StickyNav.addClass('sticky-nav-slide-visible');$(document).trigger('sticky-nav-visible');}else{$this.StickyNav.removeClass('sticky-nav-slide-visible');$(document).trigger('sticky-nav-hide');}
if(scrollCurrent>$this.StickyOffsetFull+150){$this.StickyNav.addClass('sticky-nav-slide');}else{$this.StickyNav.removeClass('sticky-nav-slide');}
if($this.sInFirst&&scrollCurrent>$this.StickyOffsetFull+150){$this.StickyNav.addClass(' sticky-nav-slide-visible sticky-up');$this.StickyNav.addClass('sticky-nav-slide');$(document).trigger('sticky-nav-visible');$this.sDirection='up';$this.sInterval=151;$this.sInFirst=false;}}else{if(scrollCurrent>$this.StickyOffset){$this.StickyNav.addClass('sticky-nav');$(document).trigger('sticky-nav-visible');}else{$this.StickyNav.removeClass('sticky-nav');$(document).trigger('sticky-nav-hide');}}
$this.sPrevious=scrollCurrent;},animateSearch:function(e){var minHeightMain=$this.StickyHeader.data('min-height');var navHeight=$this.StickyNav.outerHeight();$this.StickyOffsetFull=(minHeightMain+navHeight);$this.StickyHeader.find('.navbar-dummy').height(navHeight);},animateSearchStart:function(e){$this.sScrollAllow=false;},animateSearchDone:function(e){var minHeightMain=$this.StickyHeader.data('min-height');var navHeight=$this.StickyNav.outerHeight();$this.sScrollAllow=true;$this.sPrevious=$this.sPrevious+(navHeight-minHeightMain);},smartLevels:function(e){var windowWidth=$(window).width();$('.navbar-nav li').removeClass('cs-mm-level');$('.navbar-nav li').removeClass('cs-mm-position-left cs-mm-position-right');$('.navbar-nav li .sub-menu').removeClass('cs-mm-position-init');$('.navbar-nav > li.menu-item').not('.cs-mega-menu').each(function(index,parent){var position='cs-mm-position-right';var objPrevWidth=0;$(parent).find('.sub-menu').each(function(index,el){$(el).parent().next('li').addClass('cs-mm-level');if($(el).parent().hasClass('cs-mm-level')){$(el).parent().removeClass('cs-mm-level');position='cs-mm-position-right';objPrevWidth=0;}
var offset=$(el).offset();var objOffset=offset.left;if('cs-mm-position-right'===position&&$(el).outerWidth()+objOffset>windowWidth){position='cs-mm-position-left';}
if('cs-mm-position-left'===position&&objOffset-($(el).outerWidth()+objPrevWidth)<0){position='cs-mm-position-right';}
objPrevWidth=$(el).outerWidth();$(el).addClass('cs-mm-position-init').parent().addClass(position);});});},adaptTablet:function(e){$(document).on('touchstart',function(e){if(!$(e.target).closest('.navbar-nav').length){$('.navbar-nav .menu-item-has-children').removeClass('submenu-visible');}else{$(e.target).parents('.menu-item').siblings().find('.menu-item').removeClass('submenu-visible');$(e.target).parents('.menu-item').siblings().closest('.menu-item').removeClass('submenu-visible');}});$('.navbar-nav .menu-item-has-children').each(function(e){$(this).removeClass('submenu-visible');$(this).find('> a > .expanded').remove();if('ontouchstart'in document.documentElement){$(this).find('> a').append('<span class="expanded"></span>');}
$(this).addClass('ontouchstart'in document.documentElement?'touch-device':'');$('> a .expanded',this).on('touchstart',function(e){e.preventDefault();$(this).closest('.menu-item-has-children').toggleClass('submenu-visible');});if('#'===$('> a',this).attr('href')){$('> a',this).on('touchstart',function(e){e.preventDefault();if(!$(e.target).hasClass('expanded')){$(this).closest('.menu-item-has-children').toggleClass('submenu-visible');}});}});}};})();cscoNavigation.init();$('.toggle-offcanvas, .site-overlay').on('click',function(e){e.preventDefault();if(!$('body').hasClass('offcanvas-active')){$('body').addClass('offcanvas-transition');}else{setTimeout(function(){$('body').removeClass('offcanvas-transition');},400);}
$('body').toggleClass('offcanvas-active');});(function(){var viewport=$(window).height();var lastScrollY=0;var ticking=false;var offset=200;var update=function(){var article=$('.single-post .site-main > article');if(1===article.length){let articleHeight=$(article).innerHeight();let topPoint=$(article).offset().top;let bottomPoint=topPoint+articleHeight+offset;if(lastScrollY>topPoint&&lastScrollY+viewport<bottomPoint){$('.post-prev-next-along').addClass('pagination-visible');}else{$('.post-prev-next-along').removeClass('pagination-visible');}}
ticking=false;};var requestTick=function(){if(!ticking){window.requestAnimationFrame(update);ticking=true;}};var onProcess=function(){lastScrollY=window.scrollY;requestTick();};$(window).on('scroll',onProcess);$(window).on('resize',onProcess);$(window).on('slider-refresh',onProcess);})();function triggerSearch(){$(document).trigger('animate-search-start');var timerSearchId=setInterval(function(){$(document).trigger('animate-search');},25);setTimeout(function(){clearInterval(timerSearchId);},399);setTimeout(function(){$(document).trigger('animate-search-done');},400);}
$('.toggle-search').on('click',function(event){event.preventDefault();var container=$('#search'),field=$('input[type="search"]',container);$(this).toggleClass('toggle-close');container.toggleClass('search-open');triggerSearch();if(container.hasClass('search-open')){field.focus();}else{field.blur();}});$('#search, .search-close').on('click keyup',function(event){if(event.target.className==='search-close'||event.keyCode===27){event.preventDefault();$('.toggle-search').removeClass('toggle-close');$('#search').removeClass('search-open');$('#search input[type="search"]').blur();triggerSearch();}});var stickyElements=[];stickyElements.push('.sticky-sidebar-enabled.stick-to-top .sidebar-1');stickyElements.push('.sticky-sidebar-enabled.stick-last .sidebar .widget:last-child');$(document).ready(function(){if($.browser.mozilla){stickyElements.push('.sticky-sidebar-enabled.stick-to-bottom .sidebar-1');}
stickyElements=stickyElements.join(',');$(document).on('sticky-nav-visible',function(){var navBarHeight=$('.navbar-primary').innerHeight();$(stickyElements).css('top',32+navBarHeight+'px');});$(document).on('sticky-nav-hide',function(){$(stickyElements).css('top',32+'px');});});(function(){var initAPI=false;var process=false;var contex=[];var players=[];var attrs=[];var YTdeferred=$.Deferred();window.onYouTubePlayerAPIReady=function(){YTdeferred.resolve(window.YT);};function embedYoutubeAPI(){var tag=document.createElement('script');tag.src='https://www.youtube.com/iframe_api';var firstScriptTag=document.getElementsByTagName('script')[0];firstScriptTag.parentNode.insertBefore(tag,firstScriptTag);}
function rescaleVideoBackground(){$('.cs-video-init').each(function(){let w=$(this).parent().width();let h=$(this).parent().height();var hideControl=400;let id=$(this).attr('data-uid');if(w/h>16/9){players[id].setSize(w,w/16*9+hideControl);}else{players[id].setSize(h/9*16,h+hideControl);}});}
function initVideoBackground(){if(process){return;}
process=true;if(!initAPI){let elements=$('.cs-video-wrapper[data-video-id]');if(elements.length){embedYoutubeAPI();initAPI=true;}}
if(!initAPI){process=false;return;}
YTdeferred.done(function(YT){$('.cs-video-inner').each(function(){var isInit=$(this).hasClass('cs-video-init');var id=null;if(!isInit){id=Math.random().toString(36).substr(2,9);}else{id=$(this).attr('data-uid');}
contex[id]=this;var isActive=$(contex[id]).hasClass('active');var isInView=$(contex[id]).isInViewport();if(isInView&&!isInit){$(contex[id]).addClass('cs-video-init');$(contex[id]).attr('data-uid',id);let videoID=$(contex[id]).parent().data('video-id');let videoStart=$(contex[id]).parent().data('video-start');let videoEnd=$(contex[id]).parent().data('video-end');if(typeof videoID==='undefined'||!videoID){return;}
attrs[id]={'videoId':videoID,'startSeconds':videoStart,'endSeconds':videoEnd,'suggestedQuality':'hd720'};players[id]=new YT.Player(contex[id],{playerVars:{autoplay:0,autohide:1,modestbranding:1,rel:0,showinfo:0,controls:0,disablekb:1,enablejsapi:0,iv_load_policy:3,playsinline:1,loop:1,},events:{'onReady':function(){players[id].loadVideoById(attrs[id]);players[id].mute();},'onStateChange':function(e){if(e.data===1){$(contex[id]).parents('.cs-overlay, .cs-video-wrap').addClass('cs-video-bg-init');$(contex[id]).addClass('active');}else if(e.data===0){players[id].seekTo(attrs[id].startSeconds);}}}});rescaleVideoBackground();}
let control=$(contex[id]).parents('.cs-overlay, .cs-video-wrap').find('.cs-player-state');if(isActive&&isInit&&!$(control).hasClass('cs-player-upause')){if(isInView&&$(control).hasClass('cs-player-play')){$(control).removeClass('cs-player-play').addClass('cs-player-pause');players[id].playVideo();}
if(!isInView&&$(control).hasClass('cs-player-pause')){$(control).removeClass('cs-player-pause').addClass('cs-player-play');players[id].pauseVideo();}}});});process=false;}
$(document).on('click','.cs-player-state',function(){let container=$(this).parents('.cs-overlay, .cs-video-wrap').find('.cs-video-inner');let id=$(container).attr('data-uid');$(this).toggleClass('cs-player-pause cs-player-play');if($(this).hasClass('cs-player-pause')){$(this).removeClass('cs-player-upause');players[id].playVideo();}else{$(this).addClass('cs-player-upause');players[id].pauseVideo();}});$(document).on('click','.cs-player-stop',function(){let container=$(this).parents('.cs-overlay, .cs-video-wrap').find('.cs-video-inner');let id=$(container).attr('data-uid');$(this).siblings('.cs-player-state').removeClass('cs-player-pause').addClass('cs-player-play');$(this).siblings('.cs-player-state').addClass('cs-player-upause');players[id].pauseVideo();});$(document).on('click','.cs-player-volume',function(){let container=$(this).parents('.cs-overlay, .cs-video-wrap').find('.cs-video-inner');let id=$(container).attr('data-uid');$(this).toggleClass('cs-player-mute cs-player-unmute');if($(this).hasClass('cs-player-unmute')){players[id].unMute();}else{players[id].mute();}});$(window).on('load scroll resize scrollstop',function(){initVideoBackground();});$(document).ready(function(){initVideoBackground();});$(document.body).on('post-load',function(){initVideoBackground();});$(window).on('resize',function(){rescaleVideoBackground();});initVideoBackground();})();})(jQuery);